Bot:
  Token: "token"
  GuildId: 0
  ProductSuggestionsChannelId: 0
  MusicSuggestionsChannelId: 0
  EmbedFooter: Développé par Tom CZEKAJ
  Activity:
    Enable: true
    # Can be PLAYING, STREAMING, LISTENING or WATCHING
    Type: PLAYING
    Content: Remy v1.1.0
    # Only for streaming
    URL: null
